
spring:
  profiles:
    active: dev
---
server:
  port: 7004
  
spring:
  profiles: dev
  application:
    name: cloud-eureka-config

eureka:
  instance:
    hostname: eureka7004.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      defaultZone: http://eureka7004.com:7004/eureka/

  
  
---

server:
  port: 7004
  
spring:
  profiles: test
  application:
    name: cloud-eureka-config

eureka:
  instance:
    hostname: eureka7004.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      defaultZone: http://eureka7004.com:7004/eureka/
