spring:
  profiles:
    active: test

---
server:
  port: 8004

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.joyin.cloud.model    # 所有Model别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: cloud-provider-module-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.110:3306/cloudDB01          # 家中电脑数据库名称
    #url: jdbc:mysql://192.168.30.166:3306/cloudDB01          # 公司电脑数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/
  instance:
    instance-id: cloud-module-dev-8004
    prefer-ip-address: true

info:
  app.name: wd-springcloud1.0
  company.name: com.joyin
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8004


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.joyin.cloud.model    # 所有Model别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: cloud-provider-module-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.1.110:3306/cloudDB02          # 家中电脑数据库名称
    #url: jdbc:mysql://192.168.30.166:3306/cloudDB01          # 公司电脑数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka/
  instance:
    instance-id: cloud-module-test-8004
    prefer-ip-address: true

info:
  app.name: wd-springcloud1.0
  company.name: com.joyin
  build.artifactId: $project.artifactId$
  build.version: $project.version$
